parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     raf
    database_user:     root
    database_password: root

    mailer_transport:  gmail
    mailer_host:      
    mailer_user:       r.guigne@gmail.com
    mailer_password:   PWD:raph

    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt

    app_webmaster: moi-même

